AWSTemplateFormatVersion: "2010-09-09"

Description: "iPad用の開発環境"

# Parameters
Parameters:
  NameKeyPrefix:
    Type: String

# AWSの各リソースの定義
Resources:
  # VPCの定義
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Sub "${NameKeyPrefix}-vpc"

  # サブネットの定義
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      # サブネット単位でiPv4パブリックアドレスの割り当てを有効化
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${NameKeyPrefix}-public-subnet-1a"

  # インターネットゲートウェイの定義
  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${NameKeyPrefix}-igw"
  
  # VPCGatewayAttachment定義
  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref Igw

  # ルートテーブルの定義
  RouteTable:
    Type:  AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${NameKeyPrefix}-route-table"

  # サブネットとルートテーブルの関連付け
  SubnetRouteTable1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref RouteTable

  # インターネットゲートウェイとルートテーブルの関連付け
  TableWithIgw:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Igw


  # セキュリティグループの定義
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: This Security Group is for iPadDev
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # Railsのアプリケーションサーバー用
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        # docker用
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${NameKeyPrefix}-sg"

  # ElasticIp定義
  EIP:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: 52.194.131.96
      InstanceId: !Ref Ec21a
    DependsOn: Ec21a

  # EC2インスタンスの定義
  Ec21a:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref PublicSubnet1a
      InstanceType: t2.small
      AvailabilityZone: ap-northeast-1a
      KeyName: ipad-dev-key
      Monitoring: false
      # ここのAMIはマネジメントコンソールから確認可能
      # 中身はAmazon Linux2
      ImageId: ami-00f045aed21a55240
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${NameKeyPrefix}-Ec21a"
