AWSTemplateFormatVersion: 2010-09-09

Description: サンプルテンプレート

Resources:
  priSub1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !ImportValue myVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: Demo11
