AWSTemplateFormatVersion: 2010-09-09

Description: "第11回のライブコーディングで作成したStack"

Parameters:
  NameBase:
    Description: "基盤の名前"
    Type: String
    Default: RaisetechLive11

Resources:
  Vpc1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostNames: true
      Tags:
        - Keye: Name
          Value: !Sub vpc-${NameBase}
