AWSTemplateFormatVersion: "2010-09-09"

Description: "世界一丁寧なAWS解説をCfnでコード化"

# AWSの各リソースの定義
Resources:
  # VPCの定義
  AwsCfNewProjectVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: aws-cf-new-project-vpc

  # ElasticIp定義  
  AwsCfNewProjectElasticIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: "3.115.204.106"
      InstanceId: !Ref AwsCfNewProjectEC2
    DependsOn: AwsCfNewProjectEC2

  # EC2インスタンスの定義
  AwsCfNewProjectEC2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref AwsCfNewProjectPublicSubnet
      InstanceType: t2.micro
      AvailabilityZone: ap-northeast-1a
      KeyName: yuta-ushijima
      Monitoring: false
      # ここのAMIはマネジメントコンソールから確認可能
      # 中身はAmazon Linux2
      ImageId: ami-0ff21806645c5e492
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - !Ref AwsNewProjectSecurityGroup
      Tags:
        - Key: Name
          Value: awsCfNewProjectEc2

  # サブネットの定義
  AwsCfNewProjectPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref AwsCfNewProjectVPC
      # サブネット単位でiPv4パブリックアドレスの割り当てを有効化
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-cf-new-project-public-subnet

  # プライベートサブネットの定義
  AwsCfNewProjectPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-northeast-1d
      VpcId: !Ref AwsCfNewProjectVPC
      Tags:
        - Key: Name
          Value: aws-cf-new-project-private-subnet

  # RDS用サブネットの定義
  AwsCfNewProjectRDSSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.4.54/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref AwsCfNewProjectVPC
      Tags:
        - Key: Name
          Value: aws-cf-new-project-rds-subnet

  # インターネットゲートウェイの定義
  AwsCfNewProjectIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-cf-new-project-subnet

  # VPCGatewayAttachment定義
  AwsCfNewwProject:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AwsCfNewProjectVPC
      InternetGatewayId: !Ref AwsCfNewProjectIgw

  # ルートテーブルの定義
  AwsCfNewProjectRouteTable:
    Type:  AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AwsCfNewProjectVPC
      Tags:
        - Key: Name
          Value: aws-cf-new-project-subnet

  # サブネットとルートテーブルの関連付け
  AwsCfNewProjectRouteLocal:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AwsCfNewProjectPublicSubnet
      RouteTableId: !Ref AwsCfNewProjectRouteTable

  # インターネットゲートウェイとルートテーブルの関連付け
  AwsCfNewProjectRouteInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AwsCfNewProjectRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AwsCfNewProjectIgw

  # セキュリティグループの定義
  AwsNewProjectSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref AwsCfNewProjectVPC
      GroupDescription: This Security Group is for AwsnewProject
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 27.83.59.109/32
        # Railsのアプリケーションサーバー用
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-cf-new-project-sg

  # RDS用セキュリティグループの定義
  AwsCfNewProjectRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref AwsCfNewProjectVPC
      GroupDescription: This Security Group is for RDS of AwsnewProject
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AwsNewProjectSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-cf-new-project-sg-for-rds


  # RDSの定義
  AwsCfNewProjectRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: 5.7.23
      LicenseModel: general-public-license
      DBInstanceClass: db.t2.micro
      MultiAZ: false
      # gp2がいわゆる汎用SSD
      StorageType: gp2
      DBInstanceIdentifier: aws-cf-new-project-mysql
      MasterUsername: admin
      MasterUserPassword: adminpass
      Port: 3306
      VPCSecurityGroups:
        - !Ref AwsCfNewProjectRDSSecurityGroup
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      PubliclyAccessible: false
      DBParameterGroupName: default.mysql5.7
      OptionGroupName: default:mysql-5-7
      CopyTagsToSnapshot: false
      BackupRetentionPeriod: 1
      # モニタリングインターバルを0にする事で無効にする
      MonitoringInterval: 0
      DBName: AwsCfNewProjectMasterDB
      DBSubnetGroupName: !Ref AwsCfNewProjectSubnetGroup
      Tags:
        - Key: Name
          Value: aws-cf-new-project-rds


  # RDSのサブネットグループを定義
  AwsCfNewProjectSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: This DBSubnet Group is for AwsCfNewProjectRDS
      SubnetIds:
        - !Ref AwsCfNewProjectPrivateSubnet
        - !Ref AwsCfNewProjectRDSSubnet
      Tags:
        - Key: Name
          Value: aws-cf-new-project-rds-subnet-group
