AWSTemplateFormatVersion: "2010-09-09"

Description: "失敗するCloudformationテンプレート2"

# AWSの各リソースの定義
Resources:
  # VPCの定義
  InvalidVPC:
    Type: AWS::EC2::VPC
    Properties:
      Cidr_Block: "10.0.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: unsupported-property-vpc